"""Domain constants kept in one place so routes never use magic strings."""

BOOKING_PENDING = "PENDING"
BOOKING_CONFIRMED = "CONFIRMED"
BOOKING_FAILED = "FAILED"
BOOKING_CANCELLED = "CANCELLED"

BOOKING_STATUSES = (
    BOOKING_PENDING,
    BOOKING_CONFIRMED,
    BOOKING_FAILED,
    BOOKING_CANCELLED,
)

PAYMENT_PENDING = "PENDING"
PAYMENT_SUCCESS = "SUCCESS"
PAYMENT_FAILED = "FAILED"

PAYMENT_STATUSES = (PAYMENT_PENDING, PAYMENT_SUCCESS, PAYMENT_FAILED)
